language: python
sudo: yes

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36-ansible28
    - python: 3.6
      env: TOXENV=py36-ansible27
    - python: 3.6
      env: TOXENV=py36-ansible26
    - python: 3.6
      env: TOXENV=py36-ansible25
    - python: 2.7
      env: TOXENV=py27-ansible24
    - python: 2.7
      env: TOXENV=py27-ansible23
    - python: 2.7
      env: TOXENV=py27-ansible22
    - python: 2.7
      env: TOXENV=py27-ansible21
    - python: 2.7
      env: TOXENV=py27-ansible20

install:
  - pip install tox

script:
  - tox

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/

before_cache:
  - rm -f ${HOME}/.cache/pip/log/debug.log

cache:
  directories:
    - ${HOME}/.cache/pip
