---
# file: oracle-java/tasks/check_environment.yml
#
# task to set host facts:
#   - Java is installed?
#   - which Java version is installed?
#

# determine if Java is already installed

- name: register oracle_java_installed
  shell: "which java"
  register: oracle_java_task_installed
  ignore_errors: yes
  changed_when: False
# oracle_java_installed.rc == 0 : installed
# oracle_java_installed.rc == 1 : not installed

- name: echo oracle_java_task_installed
  debug:
    msg="oracle_java_task_installed={{ oracle_java_task_installed }}"
  when: oracle_java_task_installed is defined
  tags:
    - debug

- name: set fact oracle_java_installed
  set_fact:
    oracle_java_installed={{ oracle_java_task_installed.rc == 0 }}
  changed_when: False

- name: echo oracle_java_installed
  debug:
    msg="oracle_java_installed={{ oracle_java_installed }}"
  when: oracle_java_installed is defined
  tags:
    - debug


# determine which Java version is installed

- name: if Java is installed, check version
  shell: java -version 2>&1 | head -n 1 | awk '{ print $3 }' | awk -F '"' '{ print $2 }'
  when: oracle_java_installed
  register: oracle_java_task_version
  changed_when: False

- name: echo oracle_java_task_version
  debug:
    msg="oracle_java_task_version={{ oracle_java_task_version }}"
  when: oracle_java_task_version is defined
  tags:
    - debug

- name: set fact oracle_java_installed_version
  set_fact:
    oracle_java_version_installed={{ oracle_java_task_version.stdout }}
  when: oracle_java_installed
  changed_when: False

- name: echo oracle_java_version_installed
  debug:
    msg="oracle_java_version_installed={{ oracle_java_version_installed }}"
  when: oracle_java_version_installed is defined
  tags:
    - debug

- name: echo oracle_java_version_string
  debug:
    msg="oracle_java_version_string={{ oracle_java_version_string }}"
  when: oracle_java_version_string is defined
  tags:
    - debug
