---
# tasks file

## include OS family specific task file

- name: if debian, include family specific task file
  include: "os_family/debian.yml"
  when: ansible_os_family| lower == 'debian'

- name: check if operating system is suported
  fail:
    msg: "The operating system ({{ ansible_os_family }}) of the target machine ({{ inventory_hostname }}) is not currently supported."
  when: os_supported is not defined


## generic tasks

- apt:
    update_cache=yes
    cache_valid_time={{ ppa_webupd8_cache_valid_time }}
