---
# file: oracle-java/tasks/debian/main.yml
#
# Task file to install Oracle Java Development Kit in a system with a Debian based Linux distribution.
#

- name: debian | (ubuntu or mint) | add java ppa repo
  apt_repository:
    repo=ppa:webupd8team/java
    state=present
    codename='{{ oracle_java_ppa_mint[ansible_lsb.codename]|default(ansible_lsb.codename) }}'
  become: yes
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Linuxmint'

- block:
  - name: debian | ensure the webupd8 launchpad apt repository key is present
    apt_key:
      id=0xC2518248EEA14886
      keyserver=keyserver.ubuntu.com
      state=present
    become: yes

  - name: debian | ensure the webupd8 launchpad apt repository is present
    apt_repository:
      repo="{{ item }} http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main"
      update_cache=yes
      state=present
    with_items:
      - deb
      - deb-src
    become: yes

  when: ansible_distribution == 'Debian'

- name: debian | set license as accepted
  debconf: name='oracle-java{{ oracle_java_version }}-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  become: yes

- name: debian | ensure Java is installed
  apt:
    name="oracle-java{{ oracle_java_version }}-installer"
    state={{ oracle_java_state }}
    cache_valid_time={{ oracle_java_cache_valid_time }}
    update_cache=yes
  register: oracle_java_task_apt_install
  become: yes

- name: debian | set Java version as default
  apt:
    name="oracle-java{{ oracle_java_version }}-set-default"
    state=latest
  register: oracle_java_task_set_default
  when: oracle_java_set_as_default
  become: yes

- name: debian | in case there were changes, check host environment again
  include: ../check_environment.yml
  when: oracle_java_task_apt_install|changed or oracle_java_task_set_default|changed
