---
# file: oracle-java/tasks/redhat/main.yml
#
# Task file to install Oracle Java Development Kit in a system with a Redhat based Linux distribution.
#

- name: download Java RPM
  shell:
    "curl -L  -H 'Cookie:oraclelicense=accept-securebackup-cookie' -o {{ oracle_java_dir_source }}/{{ oracle_java_rpm_filename }} {{ oracle_java_rpm_url }}"
  args:
    creates: "{{ oracle_java_dir_source }}/{{ oracle_java_rpm_filename }}"
  register: oracle_java_task_rpm_download
  sudo: yes
  tags:
    - installation

- name: install RPM
  yum:
    name="{{ oracle_java_dir_source }}/{{ oracle_java_rpm_filename }}"
    state=present
  when: not oracle_java_task_rpm_download|skipped
  sudo: yes
  tags:
    - installation

- name: set Java version as default
  alternatives:
    name="{{ item.exe }}"
    link="/usr/bin/{{ item.exe }}"
    path="{{ item.path }}/{{ item.exe }}"
  when: oracle_java_set_as_default
  with_items:
    - { path: "{{ oracle_java_home }}/jre/bin", exe: 'java' }
    - { path: "{{ oracle_java_home }}/jre/bin", exe: 'keytool' }
    - { path: "{{ oracle_java_home }}/bin", exe: 'javac' }
    - { path: "{{ oracle_java_home }}/bin", exe: 'javadoc' }
  sudo: yes
  when: oracle_java_task_rpm_download|changed or (oracle_java_installed and oracle_java_version_installed != oracle_java_version_string)
  register: oracle_java_task_set_default

- name: in case there were changes, check host environment again
  include: ../check_environment.yml
  when: not oracle_java_task_rpm_download|skipped or oracle_java_task_set_default|changed
